repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
